version: "3.9"

services:
  db:
    image: postgres:16
    container_name: capi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: capi_password
      POSTGRES_DB: capi_platform
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
